name: Deploys site to gh_pages branch

on:
  push:
  - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.x'
  
    - run: |
        bundle install
        bundle exec jekyll build